name: Main

on: workflow_dispatch

jobs:
  Android:
    uses: ./.github/workflows/build.yml
    with:
      name: Android
      os: ubuntu-latest
      setupCommand: ":"
      buildArgs: "-ONLY_ARMV7"
      artifactName: androidBuild
      artifactPath: "export/release/android/bin/app/build/outputs/apk/release/*.apk"
